all: forking exec infloop exitcode forkexec

infloop: infloop.c
	gcc infloop.c -o inf

exec: arg.c
	gcc arg.c -o arg

forking: forking.c
	gcc forking.c -o forking

exitcode: exitcode.c
	gcc exitcode.c -o exitcode

forkexec: forkexec.c
	gcc forkexec.c -o forkexec
