all:	infinite alarmClock clock showCmdArg ex3

ex3: ex3.c
	gcc -Wall -o ex3 ex3.c

infinite: infinite.c
	gcc -Wall -o infinite infinite.c

alarmClock: alarmClock.c
	gcc -Wall -o alarmClock alarmClock.c

clock:	clock.c
	gcc -Wall -o clock clock.c

showCmdArg:	showCmdArg.c
	gcc -Wall -o showCmdArg showCmdArg.c

clean:
	rm -rf infinite alarmClock clock showCmdArg ex3
